apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oac-prod-etcd-encryption-key
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "0"
  target:
    name: oac-prod-etcd-encryption-key
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: etcd-encryption-key
