apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oac-prod-github-oauth-client-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oac-prod-github-oauth-client-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: cluster/oac-dev-workload0/github-oauth-client-secret
