apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: oac-prod
  namespace: clusters
  labels:
    lars-test-label: foo
spec:
  controllerAvailabilityPolicy: HighlyAvailable
  dns:
    baseDomain: apps.infra.oac.int.massopen.cloud
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: lvms-vg0
        type: PersistentVolume
    managementType: Managed
  fips: false
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    agent:
      agentNamespace: hardware-inventory
    type: Agent
  pullSecret:
    name: pull-secret
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.21.0-multi
  secretEncryption:
    aescbc:
      activeKey:
        name: oac-prod-etcd-encryption-key
    type: aescbc
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: Route
        route:
          hostname: api-oac-prod.apps.infra.oac.int.massopen.cloud
    - service: Ignition
      servicePublishingStrategy:
        type: Route
        route:
          hostname: ignition-oac-prod.apps.infra.oac.int.massopen.cloud
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
        route:
          hostname: konnectivity-oac-prod.apps.infra.oac.int.massopen.cloud
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
        route:
          hostname: oauth-oac-prod.apps.infra.oac.int.massopen.cloud
    - service: OIDC
      servicePublishingStrategy:
        type: Route
  issuerURL: "https://oac-clusters-oidc.s3.us-east-1.amazonaws.com/oac-dev-workload0"
  sshKey:
    name: oac-ssh-key
