apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: oac-prod
  namespace: metallb-system
spec:
  addresses:
    - 10.20.3.20/32
  serviceAllocation:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: clusters-oac-prod
