apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: oac-prod-admin-credentials
  namespace: clusters
spec:
  secretStoreRefs:
    - name: aws-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: oac-prod-admin-kubeconfig
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/oac-prod
          property: adminKubeconfig
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: oac-prod-kubeadmin-password
  namespace: clusters
spec:
  secretStoreRefs:
    - name: aws-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: oac-prod-kubeadmin-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/oac-prod
          property: kubeadminPassword
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: oac-prod-etcd-encryption-key
  namespace: clusters
spec:
  secretStoreRefs:
    - name: aws-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: oac-prod-etcd-encryption-key
  data:
    - match:
        secretKey: key
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/oac-prod
          property: etcdEncryptionKey
