apiVersion: v2
name: nvidia-network-operator
description: Install NVIDIA Network operator
type: application
version: 0.1.0
dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
