clusterDomain: ""

keycloak:
  issuerUrl: ""
  clientId: ""
  secretRef:
    name: keycloak-oidc-client-secret
    key: clientSecret

externalSecret:
  secretStore: aws-secrets-manager
  remoteKey: ""
