apiVersion: v2
name: github-group-sync
description: GitHub Group Sync Operator
version: 0.1.0
type: application

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
