{{- $hub := required "hubName must be set" .Values.hubName }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-components
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - component: openshift-gitops
          - component: nmstate
          - component: external-secrets
          - component: lvmcluster
          - component: metallb
          - component: cert-manager
          - component: patch-operator
          - component: node-labels
          - component: portworx
          - component: oac-simple-rbac
          - component: external-dns-operator
          - component: cluster-certificates
          - component: acm
          - component: hcp-config
          - component: acm-gitops-integration
          - component: acm-placements
  template:
    metadata:
      name: "hub-{{`{{component}}`}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/CCI-MOC/oac-apps.git
        targetRevision: main
        path: "charts/{{`{{component}}`}}"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - "/values/{{ $hub }}/{{`{{component}}`}}.yaml"
            - "/values/{{ $hub }}/local-cluster/{{`{{component}}`}}.yaml"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
