{{ range .Values.projects }}
{{- if .members }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  labels:
    massopen.cloud/project: "{{ .name }}"
  name: "project-{{ .name }}-edit"
users:
{{ .members | toYaml }}
---
{{- end }}
{{ end }}
