{{ range .Values.projects }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  labels:
    massopen.cloud/project: "{{ .name }}"
  name: "project-{{ .name }}"
users:
{{ .members | toYaml }}
---
{{ end }}
