{{ range .Values.groups }}
{{- if .members }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  labels:
    massopen.cloud/group: "{{ .name }}"
  name: "{{ .name }}"
users:
{{ .members | toYaml }}
---
{{- end }}
{{ end }}
