clusterDomain: infra.oac.int.massopen.cloud
keycloak:
  issuerUrl: "" # e.g. https://keycloak.example.com/realms/moc
  clientId: "" # OIDC client ID for this cluster
externalSecret:
  remoteKey: "" # AWS Secrets Manager key containing the Keycloak client secret
certificate:
  issuer_name: letsencrypt-prod-dns01
