addressPools:
  - name: default
    addresses:
      - 10.20.3.200-10.20.3.250
  - name: hosted-clusters-ingress
    addresses:
      - 10.20.3.10/32
    serviceAllocation:
      namespaceSelectors:
        - matchLabels:
            kubernetes.io/metadata.name: openshift-ingress
      serviceSelectors:
        - matchLabels:
            ingresscontroller.operator.openshift.io/owning-ingresscontroller: hosted-clusters
