clientID: "1bd59d9431653b8aaccd"
secretName: github-oauth-client-secret
mappingMethod: claim
organizations: []
teams:
  - CCI-MOC/open-accelerator

externalSecret:
  secretStore: aws-secrets-manager
  secretStoreType: ClusterSecretStore
  remoteKey: "cluster/oac-infra-dev/github-oauth-client-secret"
