aws:
  region: us-east-1
  roleArn: "arn:aws:iam::574733721584:role/cert-manager-oac-infra-dev"
  hostedZoneID: "Z07788262L24MNHAVE489" # Route53 zone ID for int.massopen.cloud
letsencrypt:
  email: admin@massopen.cloud
  server: https://acme-staging-v02.api.letsencrypt.org/directory
