ingressController:
  enabled: true
  # Must not overlap with the default IngressController's domain. OpenShift
  # rejects both exact matches and subdomains.
  domain: hcp.oac.massopen.cloud
  addresses:
    - 10.20.9.10/32
