namespace: redhat-ods-operator
operatorgroup:
  targetNamespaces: false
subscription:
  channel: stable
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
