namespace: nvidia-maintenance-operator
operatorgroup:
  targetNamespaces: true
subscription:
  channel: stable
  name: nvidia-maintenance-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
