{{- if .Values.clustersecretstores.aws.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clustersecretstores.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.namespace }}
{{- end }}
