{{- if index .Values.clustersecretstores "openshift-config" "enabled" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: openshift-config
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ .Values.namespace }}
      auth:
        serviceAccount:
          name: eso-openshift-config-reader
          namespace: {{ .Values.namespace }}
{{- end }}
