{{- if .Values.clustersecretstores.aws.enabled }}
{{- $roleArn := required "clustersecretstores.aws.roleArn is required" .Values.clustersecretstores.aws.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: {{ $roleArn }}
{{- end }}
