{{- if .Values.clusterissuers.aws.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: {{ required "clusterissuers.aws.roleArn is required" .Values.clusterissuers.aws.roleArn }}
{{- end }}
