apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: {{ required "aws.roleArn is required" .Values.aws.roleArn }}
