namespace: openshift-cluster-observability-operator
operatorgroup:
  targetNamespaces: false
subscription:
  channel: stable
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
