namespace: openshift-nfd
operatorgroup:
  targetNamespaces: true
subscription:
  channel: stable
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
