namespace: external-secrets

subscription:
  channel: stable
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

aws:
  region: us-east-1
  roleArn: ""

serviceAccount:
  name: external-secrets-sa
