namespace: external-secrets

subscription:
  channel: stable-v1
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

aws:
  region: us-east-1
  roleArn: ""

serviceAccount:
  name: external-secrets-sa
