namespace: external-secrets

subscription:
  channel: stable-v1
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

clusterissuers:
  aws:
    enabled: true
    region: us-east-1
    roleArn: ""

  openshift-config:
    enabled: false

serviceAccount:
  name: external-secrets-sa
