apiVersion: v2
name: openshift-gitops
description: OpenShift GitOps operator and ArgoCD instance
version: 0.1.0
type: application

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
