{{- $clusterDomain := required "clusterDomain is required" .Values.clusterDomain }}
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  labels:
    nerc.mghpcc.org/kustomized: "true"
  name: cluster
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
      - names:
          - 'api.{{ $clusterDomain }}'
        servingCertificate:
          name: {{ .Values.certificate.api_certificate_name }}
