{{- if and .Values.keycloak.issuerUrl .Values.keycloak.clientId .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc-client-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.keycloak.secretRef.name }}
  data:
    - secretKey: {{ .Values.keycloak.secretRef.key }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}
