{{ if .Values.certificates.api.enabled }}
{{- $clusterDomain := required "clusterDomain is required" .Values.clusterDomain }}
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  namespace: openshift-config
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
      - names:
          - '{{ .Values.clusterAPIDomainName | default (printf "api.%s" $clusterDomain) }}'
        servingCertificate:
          name: {{ .Values.certificates.api.certificate_name }}
{{ end }}
