{{- range .Values.externaldns }}
{{- if .externalSecret }}
{{- if .externalSecret.remoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .credentials }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .externalSecret.secretStore }}
    kind: {{ .externalSecret.secretStoreType | default "ClusterSecretStore" }}
  target:
    name: {{ .credentials }}
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: {{ .externalSecret.remoteKey }}
        property: access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: {{ .externalSecret.remoteKey }}
        property: secret_access_key
{{- end }}
{{- end }}
{{- end }}
