{{- $hub := required "hubName must be set" .Values.hubName }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: pure-cosi
 namespace: openshift-gitops
spec:
 generators:
   - clusterDecisionResource:
       configMapRef: acm-placement
       labelSelector:
         matchLabels:
           cluster.open-cluster-management.io/placement: portworx-clusters
       requeueAfterSeconds: 180
 template:
   metadata:
     name: "{{`{{name}}`}}-pure-cosi"
   spec:
     project: default
     source:
       repoURL: https://github.com/CCI-MOC/oac-apps.git
       targetRevision: main
       path: "kustomize/pure-cosi/overlays/{{`{{name}}`}}"
     destination:
       server: "{{`{{server}}`}}"
       namespace: pure-cosi-system
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
       syncOptions:
         - CreateNamespace=true
       retry:
         limit: 5
         backoff:
           duration: 30s
           factor: 2
           maxDuration: 10m
