apiVersion: v2
name: sriov-network-operator
description: Install SR-IOV Network operator
type: application
version: 0.1.0
dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
