namespace: openshift-sriov-network-operator
operatorgroup:
  targetNamespaces: true
subscription:
  channel: stable
  name: sriov-network-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
