apiVersion: v2
name: metallb
description: Deploy MetalLB with L2 advertisement
type: application
version: 0.1.0

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
