namespace: metallb-system

operatorgroup:
  targetNamespaces: false

subscription:
  name: metallb-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable

# addressPools:
#   - name: default
#     addresses:
#       - 192.168.1.100-192.168.1.200
#   - name: ingress
#     addresses:
#       - 192.168.1.50/32
#     serviceAllocation:
#       namespaceSelectors:
#         - matchLabels:
#             kubernetes.io/metadata.name: openshift-ingress
