apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nvidia-maintenance-operator
  namespace: nvidia-maintenance-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - nvidia-maintenance-operator
