{{- if .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: px-pure-secret
  namespace: "{{ .Values.targetNamespace | default .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: px-pure-secret
  data:
    - secretKey: pure.json
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}
