apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage-network
  namespace: portworx
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "br-storage",
      "type": "bridge",
      "bridge": "br-storage",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ required "network.cidr is required" .Values.network.cidr }}",
        "range_start": "{{ required "network.range.start is required" .Values.network.range.start }}",
        "range_end": "{{ required "network.range.end is required" .Values.network.range.end }}",
        "routes": {{ .Values.network.routes | default (list) | toJson }}
      }
    }
