apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: "{{ .Values.targetNamespace | default .Release.Namespace }}"
  name: portworx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - portworx
