apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
{{ if .Values.portworx.is_default_storage_class }}
    storageclass.kubernetes.io/is-default-class: 'true'
{{ end }}
    opendatahub.io/sc-config: {{ dict
      "displayName" .Values.portworx.dashboard.display_name
      "isEnabled" true
      "isDefault" .Values.portworx.is_default_storage_class
      "lastModified" .Values.portworx.dashboard.last_modified
      "accessModeSettings" .Values.portworx.dashboard.access_modes
      | toJson | quote }}
  labels:
    operator.libopenstorage.org/managed-by: portworx
  name: pure-fb-nfsv4
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - tcp
parameters:
  backend: pure_file
  pure_nfs_server: {{ .Values.portworx.nfs_server }}
  pure_nfs_policy: {{ .Values.portworx.nfs_policy }}
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
