baseDomain: apps.infra.oac.int.massopen.cloud
managementCluster: oac-infra-dev
hcpInternalDomain: hcp.infra.oac.int.massopen.cloud

clusterName: oac-prod

issuerURL: "https://oac-clusters-oidc.s3.us-east-1.amazonaws.com/oac-dev-workload0"

services:
  OAuthServer:
    servicePublishingStrategy:
      type: Route
      route:
        hostname: oauth-oac-prod.apps.infra.oac.int.massopen.cloud

oauth:
  identityProviders:
    - name: github
      type: GitHub
      mappingMethod: claim
      github:
        clientID: "1234567890abcdef0123"
        clientSecret:
          name: oac-prod-github-oauth-client-secret
        teams:
          - CCI-MOC/open-accelerator

externalSecrets:
  - name: oac-prod-github-oauth-client-secret
    spec:
      target:
        name: oac-prod-github-oauth-client-secret
      data:
        - secretKey: clientSecret
          remoteRef:
            key: cluster/oac-infra-dev/hostedcluster/oac-prod/github-oauth-client-secret

nodePools:
  - name: compute
    replicas: 3
    agentLabelSelector:
      openstack/resource-class: fc830
      massopen.cloud/cluster: oac-prod
  - name: gpu
    replicas: 2
    agentLabelSelector:
      openstack/resource-class: lenovo-sd665nv3-h100
      massopen.cloud/cluster: oac-dev-workload0

clusterLabels:
  massopen.cloud/feature-gpu: "true"
  massopen.cloud/feature-github-oauth: "true"
  massopen.cloud/feature-portworx: "true"

dns:
  enabled: true
  records:
    - name: api-internal
      hostname: api-oac-prod.apps.infra.oac.int.massopen.cloud
      targets:
        - 192.168.1.1
        - 192.168.1.2
        - 192.168.1.3
    - name: ingress
      hostname: "*.apps.oac-prod.apps.infra.oac.int.massopen.cloud"
      target: 192.168.1.1
