{{- $group := required "group is required" .Values.group }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: {{ $group }}-olm
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch

