{{- if .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-storage-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.secretStoreType | default "ClusterSecretStore" }}
  target:
    name: object-storage-certificate
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: tls.key
{{- end }}
