apiVersion: v1
kind: Service
metadata:
  name: object-storage-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: object-storage-proxy
spec:
  type: ClusterIP
  clusterIP: {{ required "service.clusterIP is required" .Values.service.clusterIP }}
  selector:
    app.kubernetes.io/name: object-storage-proxy
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
