{{- if .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentialsSecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.secretStoreType }}
  target:
    name: {{ .Values.credentialsSecret.name }}
  data:
    - secretKey: appId
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: appId
    - secretKey: privateKey
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: privateKey
{{- end }}
