apiVersion: v2
name: nmstate
description: Install Kubernetes nmstate operator
type: application
version: 0.1.0

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
