namespace: openshift-nmstate

operatorgroup:
  targetNamespaces: true

subscription:
  channel: stable
  name: kubernetes-nmstate-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
