{{- $apiServerStrategy := dig "APIServer" "servicePublishingStrategy" nil .Values.services }}
{{- $isLoadBalancer := or (not $apiServerStrategy) (eq (dig "type" "" $apiServerStrategy) "LoadBalancer") }}
{{- if and .Values.apiServerIP $isLoadBalancer }}
{{- $clusterName := required "clusterName is required" .Values.clusterName }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $clusterName }}-apiserver
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.apiServerIP }}/32
  serviceAllocation:
    namespaces:
      - {{ .Values.namespace }}-{{ $clusterName }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $clusterName }}-apiserver
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ $clusterName }}-apiserver
{{- end }}
