{{- $clusterName := required "clusterName is required" .Values.clusterName }}
{{- $oauthHostname := include "hosted-cluster.oauthHostname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $clusterName }}-oauth-certificate
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  dnsNames:
    - {{ $oauthHostname }}
  duration: {{ .Values.certificate.duration }}
  issuerRef:
    kind: {{ .Values.certificate.issuerKind }}
    name: {{ .Values.certificate.issuer }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  secretName: {{ $clusterName }}-oauth-certificate
