{{- $clusterName := required "clusterName is required" .Values.clusterName }}
{{- $managementCluster := include "hosted-cluster.managementCluster" . }}
{{ if .Values.pushSecrets.kubeadmin_kubeconfig.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-admin-credentials
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRefs:
    - name: {{ .Values.secretStore.name }}
      kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-admin-kubeconfig
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: cluster/{{ $managementCluster }}/hostedcluster/{{ $clusterName }}/kubeadmin
          property: adminKubeconfig
---
{{ end }}
{{ if .Values.pushSecrets.kubeadmin_password.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-kubeadmin-password
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRefs:
    - name: {{ .Values.secretStore.name }}
      kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-kubeadmin-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cluster/{{ $managementCluster }}/hostedcluster/{{ $clusterName }}/kubeadmin
          property: kubeadminPassword
---
{{ end }}
{{ if .Values.pushSecrets.etcd.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-etcd-encryption-key
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRefs:
    - name: {{ .Values.secretStore.name }}
      kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-etcd-encryption-key
  data:
    - match:
        secretKey: key
        remoteRef:
          remoteKey: cluster/{{ $managementCluster }}/hostedcluster/{{ $clusterName }}/kubeadmin
          property: etcdEncryptionKey
{{ end }}
