{{- $clusterName := required ".Values.clusterName is required" .Values.clusterName }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-admin-credentials
  namespace: clusters
spec:
  secretStoreRefs:
    - name: {{ .Values.pushsecret.name }}
      kind: {{ .Values.pushsecret.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-admin-kubeconfig
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/{{ $clusterName }}
          property: adminKubeconfig
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-kubeadmin-password
  namespace: clusters
spec:
  secretStoreRefs:
    - name: {{ .Values.pushsecret.name }}
      kind: {{ .Values.pushsecret.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-kubeadmin-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/{{ $clusterName }}
          property: kubeadminPassword
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $clusterName }}-etcd-encryption-key
  namespace: clusters
spec:
  secretStoreRefs:
    - name: {{ .Values.pushsecret.name }}
      kind: {{ .Values.pushsecret.kind }}
  selector:
    secret:
      name: {{ $clusterName }}-etcd-encryption-key
  data:
    - match:
        secretKey: key
        remoteRef:
          remoteKey: cluster/oac-infra-dev/hostedcluster/{{ $clusterName }}
          property: etcdEncryptionKey
