apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-openshift-config
    kind: ClusterSecretStore
  target:
    name: pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .pullSecret }}` }}"
  data:
    - secretKey: pullSecret
      remoteRef:
        key: pull-secret
        property: .dockerconfigjson
