{{- if .Values.pushSecret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: object-storage-certificate
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRefs:
    - name: {{ .Values.pushSecret.secretStore.name }}
      kind: {{ .Values.pushSecret.secretStore.kind }}
  selector:
    secret:
      name: {{ .Values.certificate.secretName }}
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: {{ .Values.pushSecret.remoteKey }}
          property: tls.key
{{- end }}
