apiVersion: v2
name: cert-manager
description: Red Hat cert-manager operator with Let's Encrypt ClusterIssuer and Certificates
version: 0.1.0
type: application

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
