targetNamespace: portworx

subscription:
  channel: stable
  installPlanApproval: automatic

externalSecret:
  secretStore: aws-secrets-manager
  remoteKey: ""

portworx:
  is_default_storage_class: true
  nfs_server: nfs-server
  nfs_policy: export-policy
