namespace: portworx
operatorgroup:
  targetNamespaces: true
subscription:
  channel: stable
  name: portworx-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

externalSecret:
  secretStore: aws-secrets-manager
  remoteKey: ""

portworx:
  is_default_storage_class: true
  nfs_server: nfs-server
  nfs_policy: export-policy

network:
  cidr: ""
  range:
    start: ""
    end: ""
  routes: []

nodes: []
