{{- if .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.secretStoreType }}
  target:
    name: {{ .Values.secretName }}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}
