apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acm-observability
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: bucketconverter
    kind: SecretStore
  target:
    name: acm-observability
    template:
      data:
        thanos.yaml: |
          {{ "{{- $info := .bucketInfo | fromJson }}" }}
          type: s3
          config:
            bucket: {{ "{{ $info.spec.bucketName }}" }}
            endpoint: {{ "{{ $info.spec.secretS3.endpoint }}" }}
            access_key: {{ "{{ $info.spec.secretS3.accessKeyID }}" }}
            secret_key: {{ "{{ $info.spec.secretS3.accessSecretKey }}" }}
            insecure: false
  data:
    - secretKey: bucketInfo
      remoteRef:
        key: bucketclaim-acm-observability
        property: BucketInfo
