apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-clusters
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/CCI-MOC/oac-apps.git
    targetRevision: main
    path: managed-clusters
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
