apiVersion: v2
name: lvmcluster
description: Deploy an lvmcluster storage pool
type: application
version: 0.1.0

dependencies:
  - name: operator-library
    version: "0.1.0"
    repository: "file://../operator-library"
