---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: {{ include "spoke-cluster.clusterName" . }}
  namespace: {{ include "spoke-cluster.namespace" . }}
spec:
  clusterRef:
    name: {{ include "spoke-cluster.clusterName" . }}
    namespace: {{ include "spoke-cluster.namespace" . }}
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: {{ required "sshPublicKey must be set" .Values.sshPublicKey | quote }}
  {{- if .Values.fips }}
  kernelArguments:
    - operation: append
      value: fips=1
  {{- end }}
  agentLabels:
    cluster-name: {{ include "spoke-cluster.clusterName" . }}
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: {{ include "spoke-cluster.clusterName" . }}
