clusterName: oac-prod

issuerURL: "https://oac-clusters-oidc.s3.us-east-1.amazonaws.com/oac-dev-workload0"

services:
  OAuthServer:
    servicePublishingStrategy:
      type: Route
      route:
        hostname: oauth-oac-prod.apps.infra.oac.int.massopen.cloud

oauth:
  identityProviders:
    - name: github
      type: GitHub
      mappingMethod: claim
      github:
        clientID: "1bd59d9431653b8aaccd"
        clientSecret:
          name: oac-prod-github-oauth-client-secret
        teams:
          - CCI-MOC/open-accelerator-admins

externalSecrets:
  - name: oac-prod-github-oauth-client-secret
    spec:
      target:
        name: oac-prod-github-oauth-client-secret
      data:
        - secretKey: clientSecret
          remoteRef:
            key: cluster/oac-infra-dev/hostedcluster/oac-prod/github-oauth-client-secret

nodePools:
  - name: compute
    replicas: 3
    agentLabelSelector:
      openstack/resource-class: fc830
      massopen.cloud/cluster: oac-prod
  - name: gpu
    replicas: 2
    agentLabelSelector:
      openstack/resource-class: lenovo-sd665nv3-h100
      massopen.cloud/cluster: oac-dev-workload0

clusterLabels:
  - gpu
  - github-oauth
  - portworx

dns:
  enabled: true
  records:
    - name: api
      hostname: api.oac-prod.apps.infra.oac.int.massopen.cloud
      target: 129.10.5.101
    - name: oauth
      hostname: oauth-oac-prod.apps.infra.oac.int.massopen.cloud
      target: 129.10.5.101
    - name: ingress
      hostname: "*.apps.oac-prod.apps.infra.oac.int.massopen.cloud"
      target: 129.10.5.102
    - name: api-internal
      hostname: api-oac-prod.apps.infra.oac.int.massopen.cloud
      targets:
        - 10.20.2.110
        - 10.20.2.206
        - 10.20.2.141
