apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-keycloak-oauth
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CCI-MOC/oac-apps.git
    targetRevision: main
    path: charts/keycloak-oauth
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - /values/oac-prod-infra/keycloak-oauth.yaml
        - /values/oac-prod-infra/local-cluster/keycloak-oauth.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
