name: helm

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
      - run: |
          helm plugin install --verify=false https://github.com/helm-unittest/helm-unittest
      - run: |
          ./scripts/helm-update-deps.sh
      - run: |
          ./scripts/helm-lint-all.sh
      - run: |
          ./scripts/helm-unittest-all.sh
