{{- if .Values.addressPool }}
{{- $poolName := required "addressPool.name is required when addressPool is defined" .Values.addressPool.name }}
{{- $addresses := required "addressPool.addresses is required when addressPool is defined" .Values.addressPool.addresses }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $poolName }}
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  addresses:
{{ $addresses | toYaml | indent 4 }}
{{- end }}
